apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: "MYSQL_USER"
          value: "atividade"
        - name: "MYSQL_PASSWORD"
          value: "Password1234!"
        - name: "MYSQL_DATABASE"
          value: "atividade"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "Password1234!"
      ports:
        - containerPort: 3306
          name: mysql